global:
  resolve_timeout: 5m
  telegram_api_url: "https://api.telegram.org"

route:
  receiver: 'default'
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 30m
  routes:
  - receiver: 'telegram'
    continue: true

receivers:
- name: 'default'
- name: 'telegram'
  telegram_configs:
  - send_resolved: true
    api_url: "https://api.telegram.org"
    bot_token: TELEGRAM_BOT_TOKEN_HERE
    chat_id: TELEGRAM_CHAT_ID_HERE
    parse_mode: "HTML"
    message: '{{ template "telegram.message" . }}'

templates:
- '/etc/alertmanager/telegram.tmpl'
